config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :todos do 
    member do 
      put 'complete'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :projects

  resources :teams

  get 'events' => 'events#index', as: :events

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  has_many   :todos
  has_many   :events, as: :ownerable
  has_many   :users, :through => :accesses
  has_many   :accesses

  validates :team_id,         presence: true
  validates :user_id,         presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:team_id, :user_id, :name, :description)
    end
end

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :team_id
    = f.input :user_id
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
h1 Listing projects

table
  thead
    tr
      th Team
      th User
      th Name
      th Description
      th
      th
      th

  tbody
    - @projects.each do |project|
      tr
        td = project.team_id
        td = project.user_id
        td = project.name
        td = project.description
        td = link_to 'Show', project
        td = link_to 'Edit', edit_project_path(project)
        td = link_to 'Destroy', project, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Project', new_project_path

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.slim
- content_for :page_heading
	h1 = @project.name

div
	span 团队： 
	= link_to @project.team.name, team_path(@project.team)

.mt10
	strong 任务清单
	ul.mt10
		- todos = Todo.where(project_id: @project.id).with_status(:in_progress)
		- todos.each do |todo|
			li 
				= link_to todo.title, todo_path(todo)
				- if todo.assign_user_id
					span.ml10
						= "（#{todo.assign_user.name}）"
				span.ml10
					= link_to "编辑", edit_todo_path(todo), class: "btn btn-xs btn-primary"
				span.ml10
					= link_to "完成", complete_todo_path(todo), class: "btn btn-xs btn-success", method: :put, data: {confirm: "确定完成了任务么？"}
				span.ml10
					= link_to "删除", todo_path(todo), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "确定删除任务？"}
	
hr
.mt10
	strong 添加任务
	.row
		.col-sm-8
			- @todo = Todo.new
			= render "/todos/form"