config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :todos do 
    member do 
      put 'complete'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users
  resources :projects

  resources :teams

  get 'events' => 'events#index', as: :events

  root 'home#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  extend Enumerize

  belongs_to :creator, class_name: 'User'
  belongs_to :assign_user, class_name: 'User'
  belongs_to :assign_by_user, class_name: 'User'
  belongs_to :project
  has_many   :events, as: :eventable
  has_many   :comments

  # 没有被删除的任务
  scope :active, -> { where("status <> ?", 2) }

  enumerize :status, in: {
    in_progress:  0, 
    completed:    1,
    deleted:      2
    }, default: :in_progress, scope: :with_status, i18n_scope: "todo"

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete]
  before_action :authenticate_user!
  
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    @project = @todo.project
  end

  # PUT /todos/1/complete
  def complete
    @todo.update_attribute(:status, :completed)
    TodoEvent.create_todo_complete(current_user, @todo)
    respond_to do |format|
      format.html { redirect_to @todo.project, notice: '完成了任务' }
      format.json { render :show, status: :ok, location: @todo  }
    end
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.creator = current_user
    if todo_params[:assign_user_id].present? and not todo_params[:assign_user_id].empty?
      @todo.assign_by_user = current_user
    end

    respond_to do |format|
      if @todo.save
        TodoEvent.create_todo_create current_user, @todo
        format.html { redirect_to @todo.project, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if todo_params[:assign_user_id].present? and not todo_params[:assign_user_id].empty?
        @todo.assign_by_user = current_user
      end

      old_title = @todo.title
      old_user = @todo.assign_user
      old_deadline = @todo.deadline
      if todo_params[:assign_user_id].present? and todo_params[:assign_user_id].empty?
        @todo.assign_user_id = nil
        @todo.assign_user = nil
      end
      if @todo.update(todo_params)
        # 修改任务
        TodoEvent.create_todo_update(current_user, old_title, @todo) if @todo.title != old_title
        # 指派任务
        TodoEvent.create_todo_assign_to_user(current_user, @todo.assign_user, @todo) if !old_user.present? and @todo.assign_user.present?
        # 修改任务完成者
        TodoEvent.create_todo_update_assigned_user(current_user, old_user, @todo.assign_user, @todo) if old_user.present? and old_user != @todo.assign_user
        # 修改任务完成时间
        TodoEvent.create_todo_update_deadline(current_user, old_deadline, @todo) if old_deadline != @todo.deadline

        format.html { redirect_to @todo.project, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    # @todo.destroy
    @todo.update_attribute(:status, :deleted)
    TodoEvent.create_todo_delete(current_user, @todo)
    respond_to do |format|
      format.html { redirect_to @todo.project, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :assign_user_id, :deadline, :project_id)
    end

end

app/views/todos/_form.html.slim
= simple_form_for(@todo) do |f|
	= f.error_notification
	.form-inputs
		= f.input :title, placeholder: "任务内容", required: true
		= f.input :assign_user do
			= f.collection_select :assign_user_id, @project.users, :id, :name, { :include_blank=>true}, {class: "form-control"}
		/ - if !@project or !@todo.project_id.present?
		/ 	= f.input :project do
		/ 		= f.collection_select :project_id, Project.all, :id, :name, {}, {class: "form-control"}
		- if @project
			= f.hidden_field :project_id, :value => @project.id
		= f.input :deadline, as: :string, input_html: {class: "datepicker", "data-date-format" => "yyyy-mm-dd", value: (@todo.deadline.present? ? @todo.deadline.strftime("%Y-%m-%d") : "")}
		
	.form-actions
		= f.button :submit, value: "保存", class: "btn btn-success"

javascript:
	$(function(){
		$('.datepicker').datepicker({
			format: 'yyyy-mm-dd',
			language: 'zh-CN'
		});
	});

app/views/todos/edit.html.slim
h1 Editing todo

== render 'form'

= link_to '<< 返回项目', project_path(@project.id)

app/views/todos/index.html.slim
h1 Listing todos

table
  thead
    tr
      th Title
      th Creator
      th Assign user
      th Deadline
      th
      th
      th

  tbody
    - @todos.each do |todo|
      tr
        td = todo.title
        td = todo.creator_id
        td = todo.assign_user_id
        td = todo.deadline
        td = link_to 'Show', todo
        td = link_to 'Edit', edit_todo_path(todo)
        td = link_to 'Destroy', todo, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Todo', new_todo_path

app/views/todos/new.html.slim
h1 New todo

== render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.slim
- content_for :page_heading
	h1 = @todo.title

p
  strong 状态：
  - if @todo.status == 'deleted'
    span.label.label-danger 已删除
  - else
  	span.label.label-warning = t @todo.status, scope: 'todo'
  
  span.ml10
  strong 创建者：
  = @todo.creator.present? ? link_to(@todo.creator.name, user_path(@todo.creator) ) : "无"

  span.ml10
  strong 指派给：
  = link_to @todo.assign_user.name, user_path(@todo.assign_user) if @todo.assign_user.present?
  = "无" unless @todo.assign_user.present?

  span.ml10
  strong 截止日期：
  = @todo.deadline.present? ? @todo.deadline : "无"

= link_to '编辑', edit_todo_path(@todo)
|  |  
= link_to '<< 返回项目', @todo.project

hr 

- unless @todo.comments.empty?
	- @todo.comments.each do |c|
		= link_to c.user.name, user_path(c.user)
		br
		= c.content
		hr

h2 添加评论

- @comment = Comment.new
- @comment.todo_id = @todo.id
= render "/comments/form"